### ISSUE TITLE
windows builds throwing strange errors

### ISSUE THREAD

**Issue by ultra-sonic** [CGRU/cgru#142] opened 2015-08-05 14:59 UTC
Afanasy is not working on my machine on windows 8...
afanasy 2.0.4 and also 2.0.6

when afwatch wants to connect server says:
AFERROR: readdata: read: No error
AFERROR: af::msgread: can't read message header, bytes = -1 (< Msg::SizeHeader).

when i start afrender its own log says:
AFERROR: af::msgread: can't read message header, bytes = -1 (< Msg::SizeHeader).
AFERROR: msgsendtoaddress: Reading binary answer failed.

Could it be a firewall/network issue? All applications are running on my local workstation...no network involved.

**Comment by timurhai** [comment] 2015-08-17 15:17
Hi.
I was at vacation.
So, the issue is still exists?

**Comment by ultra-sonic** [comment] 2015-08-19 08:19
Yes...i think so...have stopped testing...does it work for you?

**Comment by timurhai** [comment] 2015-08-19 10:24
Hi. Yes. About a half of windows workstations at my work are 8 (other are 7).

**Comment by mayaweb** [comment] 2015-09-16 18:11
Hello friends,
I have also this error message in the bottom all the time in the console window.
I use windows 8.1. My second computer is a Laptop and it is connected as slave. But I get the message and the laptop is not in use as I see in the render window. I hope somebody can help.

Thank you

AFERROR: readdata: read: No error

AFERROR: af::msgread: can't read message header, bytes = -1 (< Msg::SizeHeader).

**Comment by timurhai** [comment] 2015-09-16 20:26
Hi.
This cat happen if something open socket, than close and nothing was wrote.
Can some other application (service) use 51000 (afanasy) port?

**Comment by mayaweb** [comment] 2015-09-16 21:45
Hi Timur,

thank you for your answer. I was looking with netstat in the console and I
didin't see something using the port 51000.
I also realized that the second computer is connected but never in use in
the afanasy render monitor. It is always free and not be used.
I spent 2 days checking the problem and I don't find a way.

Thanks

2015-09-16 22:26 GMT+02:00 Timur Hairulin <notifications@github.com>:

> Hi.
> This cat happen if something open socket, than close and nothing was wrote.
> Can some other application (service) use 51000 (afanasy) port?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CGRU/cgru/issues/142#issuecomment-140878520>.
>



-- 
Mit freundlichen Grüßen

Albertus van Butselaar



Rietzestaße 5
10409 Berlin
Deutschland

Telefon: 0049 - (0)30 - 756 35 854
Mobil: 0049 - (0)176 - 976 91 866
Fax: 0049 - (0)30 - 756 35 856

**Comment by timurhai** [comment] 2015-09-17 09:17
Have you checked firewall? Try to turn if completely off to test the problem.
ps
afanasy listening 51000, it some other does the same they will conflict
but some other application can try to connect this port - not to listen

i think that network checking applications, that scan open ports do the same, try to connect to each, than disconnect immediately, and they nothing need to send

try to scan ports on the afanasy server machine, i think you will see the same error at that time

**Comment by kurzemnieks** [comment] 2015-10-12 07:47
Hello. We are running afanasy on windows network (rendering with Blender) and getting the same errors all the time. 
There are no firewalls or anything, but still - these errors appear constantly.

---
..
Render registered.

AFERROR: af::msgread: can't read message header, bytes = -1 (< Msg::SizeHeader).

AFERROR: msgsendtoaddress: Reading binary answer failed.
AFERROR: readdata: read: No error

AFERROR: af::msgread: can't read message header, bytes = -1 (< Msg::SizeHeader).

AFERROR: msgsendtoaddress: Reading binary answer failed.
..
----

Also some render nodes get timeout errors quite often - and we can't understand why. 
And there are a lot of Dead Cycle errors - even when render job is finished, there are Dead Cycle errors showing on clients all the time and a lot.

Is afanasy well tested on Windows or it is usually used on Linux? We have been trying to solve this for couple weeks and so far without success. 

![afanasy_errors](https://cloud.githubusercontent.com/assets/1818587/10423360/7f0eb960-70ce-11e5-9253-3b6b69fe7556.png)

**Comment by timurhai** [comment] 2015-10-12 09:04
Hi.
Usually server is on linux.
What windows version are you using?

**Comment by timurhai** [comment] 2015-10-12 09:35
Wow! I just noticed how many dead cycles you have! Over 30 thousands!
After task process finished afrender sends its state (exit status and other info) to afserver.
After afserver receives this msg, it asks render to close a task.
If this message was not received in some case, render thinks that afserver have not received message about task finish and sends it again (and prints a "dead cycle" warning).
So if you have lots of "dead cycles" you have lots of messages client->server, and it can freeze server communications, for example you can reach per-process file descriptors limit.
So, when you have lots of "dead cycles", the system is already unstable and can work with a huge timeouts.
I should think about task closing more. And do something if task closing message was lost for any reason. Any message lost should not make the whole system unstable.
( unix networking is more accurate, so i do not have such problems, but i will solve it, any client server  systems should not break on any message lot - that is my fault )

**Comment by kurzemnieks** [comment] 2015-10-14 13:08
Phew.. we have been trying everything, even changed our network switch, installed linux server on virtual machine but nothing changes (tried several machines as servers). All clients run win8. 

Basically render nodes start rendering - render couple frames successfully and then this appears:

AFERROR: af::msgread: can't read message header, bytes = -1 (< Msg::SizeHeader).
AFERROR: msgsendtoaddress: Reading binary answer failed.

And after that the Dead Cycles start printing and afserver writes that 'Task is not running'.

Render node running locally on the same machine as afserver works fine - no errors!

I also tried running older client version (2.04) but the same result. 

seems like some networking error happening.. the question only is why and where.

Anyway, thanks for answering!

**Comment by timurhai** [comment] 2015-10-14 13:20
Hi.
Can you send afseerver output what this error happens.

**Comment by kurzemnieks** [comment] 2015-10-14 14:04
Server and render node outputs:
![af_server](https://cloud.githubusercontent.com/assets/1818587/10485989/991d43b2-7295-11e5-9168-dc3b7b6bacd0.png)
![af_client](https://cloud.githubusercontent.com/assets/1818587/10485990/991da33e-7295-11e5-912a-b579adf2f27b.png)

**Comment by kurzemnieks** [comment] 2015-10-14 14:08
new screen from server with message errors - they appeared when I connected with webgui and afwatch
![af_server](https://cloud.githubusercontent.com/assets/1818587/10486135/2f16956c-7296-11e5-897b-92864daf3be0.png)

**Comment by kurzemnieks** [comment] 2015-10-14 14:13
also from time to time strange error about thumbnails appear, but this is rare:
![errror](https://cloud.githubusercontent.com/assets/1818587/10486268/dc9e233a-7296-11e5-9927-f47185668d46.png)

**Comment by kurzemnieks** [comment] 2015-10-14 18:51
So, I set up everything at home on 2 win laptops and exactly the same thing happened - as soon as second pc launches render node, Aferror messages about -1 message sizes appear on both server and render node. 
Seems like a bug.

**Comment by timurhai** [comment] 2015-10-14 20:06
All laptops are windows? windows 8?

**Comment by timurhai** [comment] 2015-10-14 21:04
Can you also provide afserver and afrender logs from very start to "dead cycle" appear on that fresh systems (2 laptops).
For now i can't repeat the situation, i connected virtual win8 afrender with an ubuntu afserver.
( for now i think that the problem is on a client side, also i should try windows 8.1 )

**Comment by kurzemnieks** [comment] 2015-10-15 13:50
Hi Timur. We did some more tests today. 
We got new linux computer and we tried running server and client there. Seems like there is a bug in both windows server and client.

Linux Server + Linux Client = no errors at all
Linux Server + Win Client = all the errors, -1 size messages + Dead Cycles after a while
Windows Server + Linux Client =  errors about -1 message size on server output only. Linux client seems to runs without errors. Errors on server started as soon as i connected to webgui from linux or other win clients.
Windows Server + Windows Client = all the errors

Here are couple new screenshots from Win+Win from clean start. 

![client_errors](https://cloud.githubusercontent.com/assets/1818587/10515484/5f51bf7e-735c-11e5-80b9-7ddd8dafb1fa.png)
![server_errors](https://cloud.githubusercontent.com/assets/1818587/10515485/5f5a06d4-735c-11e5-94fa-3edf277fe2e5.png)

We are running windows 8.1 on all win machines
I also tried Windows 10 and got exactly the same results

It looks like there is something wrong with networking code for windows - bot client and server. I guess they use the same shared functions. 

Thanks,
I hope this can be fixed somehow.

**Comment by timurhai** [comment] 2015-10-16 11:25
Hi.

I installed win8.1 on a virtual machine. Now i can see this bug, but very-very rare (can't repeat, may be virtual machine network communicates faster with its hosting machine).
I guess that the bug started since 8.1. Probably some network changes ( now i am going to test win10 ).

There are some socket options that afanasy set. You right it uses the same code and for client and for server, the code is even the same for unix and windows.
Now i made all socket options configurable and changes some defaults.
See this new section in afanasy config:
https://github.com/CGRU/cgru/blob/master/afanasy/config_default.json#L189

You can get new 2.0.7 windows archive here:
http://rules.cgru.info/#/downloads/testing
And try to change (disable) something.

What i already changed (from 2.0.6):

    "af_client_dispatch_so_rcvtimeo_sec":8,
    "af_client_dispatch_so_sndtimeo_sec":8,
    "af_client_dispatch_tcp_nodelay":0,

Later client had the so_*timeo as server 2 second.
Also clients had tcp_nodelay enabled.
Now i let clients to wait server up to 8 seconds and disabled tcp_nodelay.

You can set all options to -1 to user OS default settings.
That socket options appeared when there was not win8 or 10, on a network with a linux server and win7 clients.

The main reason of this options to limit server to wait client socket, as client may have a malfunction network connection or firewall that can cause connect/read/write blocking functions hung for a long time. And this cause dispatch messages queue hung. So one malfunction client can hung the entire system. But now we can let client to wait server more, than server can wait client. I think that it better as client has only one server and server can have lots of clients, and it is a bad idea to have the save network settings.

Each option meaning you can find in windows docs (mswin has the same networking as unix)
https://msdn.microsoft.com/en-us/library/windows/desktop/ms740476(v=vs.85).aspx

ps
If you know some network expert that can consult us - will be great!

**Comment by timurhai** [comment] 2015-10-16 11:26
btw
May be a small windows network needs no turning at all.

**Comment by timurhai** [comment] 2016-04-10 15:55
New server-client architecture where client does not listen any port, and so server does not connects clients manually, make such issues obsolete. But may be some new bugs will appear. Testing needed.

**Closed by timurhai** 2016-04-10 15:55 UTC
