### ISSUE TITLE
af_render_updatetaskperiod is not being used

### ISSUE THREAD

**Issue by sebastianelsner** [CGRU/cgru#179] opened 2016-02-22 17:17 UTC
While reviewing the code I noticed that the "af_render_updatetaskperiod" seems not to be used at all. Neither the getter "getRenderUpdateTaskPeriod" nor the vars "render_updatetaskperiod" are used in the code.

**Comment by timurhai** [comment] 2016-02-23 09:44
Wow.
It seems that it`s not used for several years, from the time when afrender was written on Qt.
I occasionally dropped it rewriting the code.
This parameter can help you. Because now all 250 nodes opens TCP connection every second to update task percentage. You can setup farm to update tasks every 5 seconds, this will decrease traffic 5 times. And if it will not hung - the problem is to accept 250+ connections per second.
I will fix it.

**Comment by sebastianelsner** [comment] 2016-02-24 10:21
the same seems to be the case for "getRenderConnectRetries"

**Comment by sebastianelsner** [comment] 2016-02-24 13:51
can I manually fix the update interval for now in:
afrender, main.cpp
```
if( AFRunning )
     af::sleep_sec(5)
```;
like this?

**Comment by timurhai** [comment] 2016-02-24 13:55
Hi.
Yes, this you can do manually right now.
Later i'll fix it.
When afrender was on Qt it just calls update signal every "render_updatetaskperiod" second.
But now i want to do something little more complex.
Better to keep update task every second, to check if it was finished, but if it is not finished, send percentage only every "render_updatetaskperiod" seconds.

**Comment by timurhai** [comment] 2016-02-25 09:45
Fixed.
Will be in 2.1.0
Or you can use these 2 files to compile older versions:
https://github.com/CGRU/cgru/commit/6202f5ec43c5dc643de9f7aadab223fe0c4f6543

**Comment by timurhai** [comment] 2016-02-25 09:46
btw,
making tasks to update every 5 seconds - does it help you with the problem?

**Comment by sebastianelsner** [comment] 2016-02-26 15:13
It actually did not help. The only thing that helped wat setting "af_task_update_timeout" to "240".
It seems that that the server does not process the task update messages in time (i.e. 15 seconds, the default), and then sends out a TaskStop message to the render, which is killing the task with SIGTERM (this I see in the render logs). The task is then dispatched to another render, but the other one has still messages in the queue. The server gets confused about the tasks state and over time things get worse. I am not exactly sure this is the issue in total, but it I am relatively sure the task timeout is involved.

**Comment by timurhai** [comment] 2016-02-26 15:20
Hi.
So setting tasks to update every 5 seconds (from 1) has no effect?

**Comment by sebastianelsner** [comment] 2016-02-26 15:23
Not on the issue we have, no. Its taking load off the server, but that is not the problem.

**Comment by timurhai** [comment] 2016-03-01 09:10
"af_render_connectretries" fixed too

**Comment by timurhai** [comment] 2016-03-01 09:12
Hi.
If you still have such ability, try to change 9 to 99 in this line:
https://github.com/CGRU/cgru/blob/master/afanasy/src/server/threadacceptclient.cpp#L147
And say whether it has some result.

**Comment by eliemichel** [comment] 2016-03-03 11:00
Ok, we did not try on the actual farm because we don't want to break it while it's been running well since we increased the timeout.

I'm sure that setting this would definitely help, but I'm not sure that it would have fixed anything and replaced the task update timeout fix. Cause, if the issue was a too short wait queue, new incoming connections (beyond the 9th one) should raise "Resource temporarily unavailable" error on the render side, right? And in this case they are reported in the logs, right? I don't think that we had a lot of such errors. Maybe some, but clearly not as much as other kinds of errors.

That being said, it's right that 9 is very low, if the queue is indeed flushed only every second (do I understand it correctly - I'm not sure here).

PS: This would make an interesting `conf.json` parameter, wouln't it?

**Comment by timurhai** [comment] 2016-03-03 11:21
May be just use SOMAXCONN?
It seems that its default value is 128. And if greater argument will be provided to listen() it will be just clamped to SOMAXCONN.
If you really want to raise it you should tune it in:
/proc/sys/net/core/somaxconn

Only internal messages queue (all data was read from socket and af::Msg constructed) is flushed every second.

**Comment by eliemichel** [comment] 2016-03-03 11:24
My bad, there's indeed no wait in `threadacceptclient`.
Do you know how it is possible to monitor the state of the listen queue?

**Comment by timurhai** [comment] 2016-03-03 11:37
It accepts a new connection in threadacceptclient, than starts a new thread threadprocessmsg.
So each new socket connection raises one new thread.
This thread reads message (blocking), react on it (may be blocking) and write answer if needed (blocking).
For example we can count all threads. And print some message every 1000 threads raise.
Than monitor how often it raises 1000 threads, if every second - it is bad, i think.

If thread will print what is it doing: reading, read, writing, wrote - done. I think we will have to huge output on 100 clients. And afserver speed bottleneck will be to write this logs.

**Comment by eliemichel** [comment] 2016-03-03 11:40
I was actually talking about the OS level listen queue, which is filled between `listen()` and `accept()`, but thanks for the explanation anyway. ;)

**Comment by timurhai** [comment] 2016-03-03 11:43
I see here one more issue. With afserver architecture. It has blocking sockets. For client accept (read - write) it is not a problem, i think, as each client is being processed in its own thread. But when afserver dispatch tasks - it does it in one thread. So 1 afrender socket malfunction will hung the entire tasks dispatching. Here non-blocking i/o should be userd.
Can this issue be related to our current problem?
Tasks dispatching tread has no relation to clients accept thread.
But afserver should use non blocking tasks dispatching anyway.

**Comment by timurhai** [comment] 2016-03-03 11:47
Wait, i think this is a queue between listen() and accept(). Which was only 9. And this can be not enough for a heavy load. But this queue is moving very fast, as server just need to raise a new thread to pop this queue.

**Comment by eliemichel** [comment] 2016-03-03 11:50
Mmh let's say that we have 200 tasks to dispatch, and that the average blocking time is 100ms (because maybe some will really hang for a bit). That will mean 20s to dispatch the whole list of tasks.
So when checking for updates right after that, tasks already timed out if update messages have not been processed yet. Is this a possible scenario?

This is consistent with the fact that there are task update messages read too late, in the sens that the task has already been stopped but its update was not processed.

About the `listen`/`accept` queue, it's not about afanasy, that was a system question. ;)

**Comment by timurhai** [comment] 2016-03-03 12:11
I think that it dispatch 200 tasks for about 2 seconds on a local network. But if some hung happens it is a possible scenario to when update is already reached but render even has not received his task yet.
Then it receives it. Sends an update - but server aready sent this task to another render. In this case we an error message about render IDs mismatch. And server asks to render to stop task - and in the same messages queue - so task stop timeout may happen before stop request was delivered to afrender.

So, definitely, server -> client messages delivery should be non blocking. This can be the reason of our problem. We can try examine messages delivery delay.

btw, stop timeout is not configurable and just 5 seconds:
https://github.com/CGRU/cgru/blob/master/afanasy/src/include/afjob.h#L23
It should be configurable too.

**Comment by timurhai** [comment] 2016-03-03 12:15
And no matter whether i/o is blocking or not, better to treat that task is started (stopped) only after the message was written to socket.

**Comment by eliemichel** [comment] 2016-03-03 12:21
Yes this seems to me like a serious track to explore, and could really explain the problem we had.

**Comment by timurhai** [comment] 2016-03-03 12:35
Latest message should be there:
https://github.com/CGRU/cgru/issues/181

And this issue is already fixed.

**Closed by timurhai** 2016-03-03 12:35 UTC
Labels: bug

**Comment by ultra-sonic** [comment] 2016-03-03 12:59
Let me just add that afanasy was configured to dispatch only 3 tasks per
second at the moment using the "af_serve_tasks_speed":3 in config.json
Could it make the current problem worse if we artificially slow down the
dispatching? Or did you (Sebastian) already adjust that value?

**Comment by sebastianelsner** [comment] 2016-03-03 13:02
I put the af_serve_tasks_speed to 1 in one of our tries an this is where it stayed then. I can't tell any more if it made the problem worse or better, tho.

**Comment by ultra-sonic** [comment] 2016-03-03 13:04
Which value did @eliemichel use in his test environment?

**Comment by timurhai** [comment] 2016-03-03 13:05
Hi.
It is unlimited by default
https://github.com/CGRU/cgru/blob/master/afanasy/config_default.json#L74
And does not influence messages (tasks) delivery.
It limits jobs solving:
https://github.com/CGRU/cgru/blob/master/afanasy/src/server/threadrun.cpp#L129
So i should not be related to tasks update timeout problem.

**Comment by ultra-sonic** [comment] 2016-03-03 13:06
I know what it does and just wanted you to be aware of just in case...
